files:
  - source: src/resources/net/rptools/maptool/language/i18n_Test.properties
    translation: %original_path%%original_file_name%_%locale_with_underscore%.%file_extension%
bundles:
  - 4
  - 6
  - 8
